### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by TomberWolf** [rodel77/ModBanner#6] opened 2017-06-29 13:46 UTC
```
[15:43:53] [Server thread/INFO]: Player lost connection: Internal server error
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]: java.lang.NullPointerException
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at mx.com.rodel.modbanner.PlayerModsAPI.getPlayerMods(PlayerModsAPI.java:24)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at mx.com.rodel.modbanner.Main.lambda$on$0(Main.java:72)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:183)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:81)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:51)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:271)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[15:43:53] [Server thread/INFO] [STDERR]: [mx.com.rodel.modbanner.Main:lambda$on$0:95]:         at java.lang.Thread.run(Unknown Source)
```

**Comment by rodel77** [comment] 2017-07-01 00:16
What sponge version are you using

**Comment by TomberWolf** [comment] 2017-07-01 14:57
Latest 1.10.2 spongeforge-1.10.2-2281-5.2.0-BETA-2422

**Comment by rodel77** [comment] 2017-07-06 02:58
Ok, currently i dont have to much time to mantain this project, but i will try to check it soon!

Cheers

**Comment by rodel77** [comment] 2017-11-29 22:20
Hello, are you still having this issue? Make sure to use the latest version!

**Comment by rodel77** [comment] 2017-11-30 01:12
I found the problem, it will be fixed to the next version, its caused by a dumb human error in the forge api! Sorry for this long time without any update!

**Closed as completed by rodel77** 2017-11-30 01:12 UTC
Labels: bug
